### ISSUE TITLE
Add mobile drag support

### ISSUE THREAD

**Issue by beebase** [devstark-com/vue-circle-slider#2]
Does this slider also support dragging on mobile devices?

**Comment by Saymon-biz** [comment]
It should be. Please provide more details (device, OS, browser) when it doesn't work

**Comment by willylatorre** [comment]
Hey, 
Didn't work on latest Chrome/Android for me.

Amazing work btw!

**Comment by Saymon-biz** [comment]
@beebase @willylatorre thank you for the feedback and sorry for the delay. Drag support added, package updated. Try it out!

**Comment by andreasvirkus** [comment]
Could you also update the demo? Doesn't have drag support atm
